//Use extend bottom, as nothing at the bottom will stop this.
//Note Emily refuses to join Dorn, and cannot be in this list.


//Recorder 
IF
	Global("OHD_ritual","MYAREA",3)
	IsOverMe("X3Reb")  // Recorder
THEN
	RESPONSE #100
		SetGlobal("OHD_ritual","MYAREA",4)
		SetGlobal("X3_ritual_target","MYAREA",3)
END

IF
	Global("X3_ritual_target","MYAREA",3)
	Global("OHD_ritual","MYAREA",5)
THEN
	RESPONSE #100
		ClearAllActions()
		DisplayStringHead("X3Reb",@973)   
		Wait(1)
		ActionOverride("X3Reb",MakeUnselectable(5))
		Wait(1)
		CreateVisualEffectObject("SPFLESHS","X3Reb")  // Recorder
		ForceSpell("X3Reb",HELL_HOLD)  // Recorder
		Wait(1)
		Kill("X3Reb")  // Recorder
		ActionOverride("X3Reb",LeaveParty())
		SetGlobal("OHD_ritual","MYAREA",6)
END
//Vienxay 
IF
	Global("OHD_ritual","MYAREA",3)
	IsOverMe("X3Vie")  // Vienxay
THEN
	RESPONSE #100
		SetGlobal("OHD_ritual","MYAREA",4)
		SetGlobal("X3_ritual_target","MYAREA",4)
END

IF
	Global("X3_ritual_target","MYAREA",4)
	Global("OHD_ritual","MYAREA",5)
THEN
	RESPONSE #100
		ClearAllActions()
		DisplayStringHead("X3Vie",@974)   
		Wait(1)
		ActionOverride("X3Vie",MakeUnselectable(5))
		Wait(1)
		CreateVisualEffectObject("SPFLESHS","X3Vie")  // Vienxay
		ForceSpell("X3Vie",HELL_HOLD)  // Vienxay
		Wait(1)
		Kill("X3Vie")  // Vienxay
		ActionOverride("X3Vie",LeaveParty())
		SetGlobal("OHD_ritual","MYAREA",6)
END
