// Abduction Scripts


IF
Global("X3SaveVampire","AR0809",1)
Global("X3EmiVampire","GLOBAL",3)
Name("X3Emi",Myself)
AreaCheck("AR0809")
THEN
RESPONSE #100
SetGlobal("X3EmiVampire","GLOBAL",4)
DialogInterrupt(TRUE)
ChangeAIScript("X3Emi",OVERRIDE) // setting script back when recovered from Crypt Altar....is this even needed(?)
END


IF
Global("X3EmiVampire","GLOBAL",1)Global("X3RomanceVampire","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("X3RomanceVampire","GLOBAL",1)
Continue()
END

IF
Global("X3EmiVampire","GLOBAL",1)Global("X3RomanceVampireTeleport","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("X3RomanceVampireTeleport","GLOBAL",1)
CreateVisualEffectObject("SPDIMNDR",Myself)
Wait(2)
DestroySelf()
END
